name: Release Version Action

on:
  release:
    types: [published]  # Trigger only when a release is published

jobs:
  print-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version from release tag
      run: |
        # Extract the version from the tag reference and remove 'v' if present at the start
        VERSION=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\/v\?//')
        echo "Release version: $VERSION"
